# Site settings
title: 數字與經濟的對話
email: mylee@gm.ypu.edu.tw
description: "讓數字說真相"
logo_location: "https://placeholdit.imgix.net/~text?txtsize=30&bg=F8F8F8&txtclr=002E62&txt=LOGO&w=100&h=100"

#baseurl: "/blog/" # the subpath of your site, e.g. /blog/
#url: "http://meiyulee.github.io/blog" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
kramdown:
  input: GFM

highlighter: rouge

#Other Global Configuration
exclude: ['README.md']

excerpt_separator: <!--more-->

#show the jumbotron header on index page
show_blog_header: true
