# Site settings
title: 數字與經濟的對話
description: 讓數字自己說出經濟意義
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "http://meiyulee.github.io/blog" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Mei-Yu Lee
user_description: 
email: mylee@gm.ypu.edu.tw
twitter_username: hwasion
github_username:  meiyulee


exclude: ['package.json', 'src' , 'node_modules']
